### ISSUE TITLE
Documentation events

### ISSUE THREAD

**Issue by yoramdelangen** [Rekord/rekord#317]
Is there a list available of all events that are there at this moment?

**Comment by ClickerMonkey** [comment]
Here are some links!

https://github.com/Rekord/rekord/blob/master/src/lib/Rekord.js#L147
https://github.com/Rekord/rekord/blob/master/src/lib/Database.js#L173
https://github.com/Rekord/rekord/blob/master/src/lib/Promise.js#L28
https://github.com/Rekord/rekord/blob/master/src/lib/Model.js#L39
https://github.com/Rekord/rekord/blob/master/src/lib/collections/Collection.js#L47 (documented)
https://github.com/Rekord/rekord/blob/master/src/lib/collections/Page.js#L17

You'll notice some of them have multiple events in one value - that's so you can things like:

```
// Called whenever any of the load functions are complete (local, remote, or none specified)
Task.Database.once( Rekord.Database.Events.Loads, function() {} );
```

Thanks for your patience with the level of documentation in the project - that's my current task and I hope to complete it all before July.

**Comment by yoramdelangen** [comment]
The current API documentation is already good in comparison with other scripts/frameworks/ORM's. Is it an idea to add small how-to usage snippets? 

For example what I tried to achieve with the events is to trigger something when the database is loaded or unloaded. When I do something like `Task.Database.once( Rekord.Database.Events.Loads, function() {} );` Its not working nor `Rekord.on(Rekord.Database.Events.Loads, function() {});` in both ways its not get triggered. 

Though this is still in alpha state, it got huge potential and it is pretty developer friendly! Keep up the good work!

**Comment by ClickerMonkey** [comment]
Listening for the load event is probably a bad example - since it may have already triggered. I added the ready function for this purpose;

```javascript
Task.ready (function () {
   // do something since now that its been loaded locally, remotely, or both.
});
```

Was it coincidental that you actually wanted to listen for the load event - or are there other events you're trying to listen to?

**Comment by ClickerMonkey** [comment]
Also, once you define your models with the Rekord function, you need to call Rekord.load (). That might be your issue as well?
