### ISSUE TITLE
DietJS Support?

### ISSUE THREAD

**Issue by topcheese** [Rekord/rekord#330]
Hi, I'm thinking of using Semantic-UI with RekordJS and DietJS.  Perhaps maybe an example as an alternative to Express?

**Comment by ClickerMonkey** [comment]
Looking into DietJS, I'll try to get back to you within a day or two!

**Comment by topcheese** [comment]
I tried to create a node module using Rekord from npm, but couldn't get it to work with DietJS from node. Thanks a lot!

**Comment by ClickerMonkey** [comment]
Rekord doesn't have a backend by default, if you're using it in node which
backend were you trying to get it to work with? (Firebase, pouchdb, a rest
server, etc are all supported backends atm)

**Comment by topcheese** [comment]
Your backend StorkJS, and PubSubJS.

**Comment by ClickerMonkey** [comment]
StorkJS saves data in the browser and PubSubJS sends live data between
browsers, but you would still need something that implements Rekord.rest to
save your data to a database which I assume you want to do. ATM Rekord
doesn't have a node backend that saves to a database.

**Comment by topcheese** [comment]
I see, except firebase.

**Comment by ClickerMonkey** [comment]
Yeah, although I haven't tested the firebase plugin in node.

**Comment by topcheese** [comment]
In the case of dietjs, you can use mysql, and mongo.

**Comment by ClickerMonkey** [comment]
Rekord in its current state is really geared to client-side use - although you could get it to work in node talking to mysql or mongo, the API isn't that friendly when developing in node. (there's quite a few things I would want to add before I would say Rekord is a library that's useful in node).

What features of Rekord drew you to it?

**Comment by topcheese** [comment]
Pretty much all of the features that you already have listed, and it seemed that you've put a lot of work into it.  I've played with quite a few orm's, but Rekord looks like one of the easiest to work with, but also quite powerful. It is also a small project, and that's what I'm looking for. I am by no means an expert, but I've played around with a lot of code, and I think I can actually do something with your framework.  I'm just trying to do an online recipe database that you can share with friends, and you also have the Unit code that l could make use of.  Client-side use is fine, I should be able to use the JQuery-rest interface with Semantic-ui to access DietJs.  I've also been trying to avoid Angular and Express, but if I want to use Rekord, I may have to get use to them.  You also seemed like you would be accessible.

**Comment by ClickerMonkey** [comment]
You don't need to use angular (or any other library) to use Rekord - however I do have a useful rekord-angular binding to keep angular applications up to date with real-time changes. jQuery will work just fine! If you want to know when to update the UI for a non-angular application just listen with `modelOrSearch.$change( callback )` or `collectionOrDatabaseOrPage.change( callback )`. Good luck on trying to use Rekord. I do hope to have a proper node implementation in the future - I've always wanted to be able to use the same ORM in the front-end and back-end (saves on defining, you can use the same validation logic, and you could use the same migrations).

**Comment by ClickerMonkey** [comment]
Closing this issue for now - since Node isn't supported at the moment this request can't be worked on. I'll make sure to reference this issue when the issue to support Node is added.
